development:
  adapter: postgresql
  encoding: unicode
  database: gonencmete
  pool: 5
  username: gonencmete
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gonencmete
  pool: 5
  username: gonencmete
  password:
